---
- hosts: monitor
  gather_facts: no
  become: yes

  roles:
    - role: network
      vars:
        network: test

    - role: prometheus
      vars:
        create_dir: true
        copy_config: true
        network: test
        version: v2.9.2

    - role: grafana
      vars:
        create_dir: true
        network: test
        version: 6.1.6

    - role: node-exporter
      vars:
        network: test
        version: v0.17.0

    - role: rmq-exporter
      vars:
        network: test
        version: v1.0.0-RC6.1

    - role: cadvisor
      vars:
        network: test
        version: v0.33.0
