---
#task for install Crawler-UI
- name: Run docker with Crawler-UI
  docker_container:
    name: crawler-ui
    image: "rustsh/crawler-ui:{{ version }}"
    restart_policy: unless-stopped
    state: started
    network_mode: bridge
    networks:
     - name: "{{ network }}"
    ports:
     - "80:8000"
    env:
      MONGO=mongodb
      MONGO_PORT=27017
