---
- name: Create Gitlab directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gitlab_config_dir }}"
    - "{{ gitlab_logs_dir }}"
    - "{{ gitlab_data_dir }}"

- name: Install Gitlab container
  docker_container:
    name: gitlab
    image: "{{ gitlab_image }}"
    state: started
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - "{{ gitlab_config_dir }}:/etc/gitlab"
      - "{{ gitlab_logs_dir }}:/var/log/gitlab"
      - "{{ gitlab_data_dir }}:/var/opt/gitlab"
    restart_policy: always
    env:
      GITLAB_OMNIBUS_CONFIG: |
        "external_url 'http://{{ ansible_host }}'"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
