---
- name: Register Gitlab runner
  shell: >
    docker run --network=gitlab --rm -t -i -v {{ gitlab_runner_config_dir }}:/etc/gitlab-runner gitlab/gitlab-runner register
    --non-interactive
    --executor "docker"
    --docker-image "{{ gitlab_runner_image }}"
    --url "http://{{ ansible_host }}/"
    --registration-token "TbqSww3D22hkT3CuHWRt"
    --docker-volumes "/home/{{ runner_user }}/.ssh:/root/.ssh"
    --description "docker-runner"
    --tag-list "docker,linux"
    --run-untagged="true"
    --locked="false"
    --docker-privileged="true"
  tags:
    - register
