---
- name: Register Gitlab runner
  shell: >
    docker run --rm -t -i -v {{ gitlab_runner_config_dir }}:/etc/gitlab-runner gitlab/gitlab-runner register
    --non-interactive
    --executor "docker"
    --docker-image alpine:latest
    --url "http://{{ ansible_host }}"
    --registration-token "PUT_YOUR_GITLAB_TOKEN_HERE"
    --description "docker-runner"
    --tag-list "docker,linux"
    --run-untagged="true"
    --locked="false"
  tags:
    - register
